### ISSUE TITLE
ms_ssim calculation

### ISSUE THREAD

**Issue by assafge** [VainF/pytorch-msssim#12]
first of all, thank you for sharing it with us!
while reading your code I've noticed in ssim.py line 195-6:

`msssim_val = torch.prod((mcs[:-1] ** weights[:-1].unsqueeze(1))
                            * (ssim_val ** weights[-1]), dim=0)  # (batch, )` 

if by definition:
![Screen Shot 2019-12-30 at 14 23 37](https://user-images.githubusercontent.com/18678046/71581863-0d402480-2b10-11ea-8610-8037219af72c.png)

as far as I understand, the ssim result is the product of l_m(p) and cs(p), it seems that your code will calculate:
![Screen Shot 2019-12-30 at 15 05 19](https://user-images.githubusercontent.com/18678046/71583127-d240ef80-2b15-11ea-972e-4fd8d2e42c51.png)
I think that the correct code would be:
`msssim_val = torch.prod((mcs ** weights.unsqueeze(1)),  dim=0)  * (ssim_val / cs)  # (batch, )`

**Comment by VainF** [comment]
Hi @assafge. Your code is correct and actually it is equivalent to the implementation in the repo.

Note that mcs[-1] = cs 
```python
msssim_val = torch.prod((mcs ** weights.unsqueeze(1)), dim=0) * (ssim_val / cs) ** weights[-1]
           # here we move the last cs to the end 
           = torch.prod((mcs[:-1] ** weights[:-1].unsqueeze(1)), dim=0) * (ssim_val / cs * cs)**weights[-1]
           = torch.prod((mcs[:-1] ** weights[:-1].unsqueeze(1)), dim=0) * ssim ** weights[-1]
```
![CodeCogsEqn](https://user-images.githubusercontent.com/18592211/71586450-3c2cb980-2b55-11ea-97ae-fb038c34c547.gif)

if α=β，

![CodeCogsEqn2](https://user-images.githubusercontent.com/18592211/71586470-4f3f8980-2b55-11ea-9430-834e501e9c82.gif)

**Comment by assafge** [comment]
nop, all cs in the power of relevant weight. I had some negative numbers in my ssim values resulting nan values in the ms_ssim, for now my calculus is:
`msssim_val = torch.prod((torch.sign(mcs) * abs(mcs) ** weights.unsqueeze(dim=1)), dim=0) * (ssim_val / cs)`

according to [exponents-less-than-1-return-nan](https://stackoverflow.com/questions/58786745/pytorch-math-with-exponents-less-than-1-return-nan-s)

**Comment by VainF** [comment]
Sorry for the late reply. Is it helpful to use a large C2? the negative ssim and cs is caused by the negative sigma_xy.

![$}IU$%P8F_2N_W(QW`@LCB](https://user-images.githubusercontent.com/18592211/71640449-24744300-2cc5-11ea-8dcd-e5287e2dde54.png)
