### ISSUE TITLE
MS_SSIM

### ISSUE THREAD

**Issue by ChafikBak** [VainF/pytorch-msssim#13]
Hi,

I used MS_SSIM with default **win_size=11** and default **weights = [0.0448, 0.2856, 0.3001, 0.2363, 0.1333]**

my input image size is 64x64

So, I get this error :

**RuntimeError: Calculated padded input size per channel: (8 x 8). Kernel size: (1 x 11). Kernel size can't be greater than actual input size**

**Comment by VainF** [comment]
Hi @ChafikBak.
There are 5 downsamples in ms-ssim, so your image should be larger than 11 * 2^5 = 352 with win_size=11. 

Maybe I should add some checks before execution.

**Comment by ChafikBak** [comment]
Hi @VainF 
Thanks, yes it will be nice if you add some checks according to input image size.

**Comment by VainF** [comment]
Sorry, I made a mistake on the required input size. The image size should be larger than 160 if win_size=11 because only 4 downsamplings are required for 5 levels.
