### ISSUE TITLE
Should it work with fp16 values?

### ISSUE THREAD

**Issue by hadaev8** [VainF/pytorch-msssim#17]
It doesnt work in my case
Example
https://colab.research.google.com/drive/1jK-2TAJs6W4vmjVdG_c_Fnjr1MG0USdd

**Comment by VainF** [comment]
Could you provide some debug messages?

Maybe you can try reinstall the latest version which provides a more stable ms-ssim implementation. BTW, the win_size should be odd.

**Comment by hadaev8** [comment]
I had ni error, just image from generator became flat white.
With new version it happens bit later, so probably its problem of model.
