### ISSUE TITLE
MS_SSIM throw RuntimeError: Calculated padded input size per channel: (6 x 6). Kernel size: (1 x 11). Kernel size can't be greater than actual input size

### ISSUE THREAD

**Issue by One-sixth** [VainF/pytorch-msssim#2]
MS_SSIM throw RuntimeError: Calculated padded input size per channel: (6 x 6). Kernel size: (1 x 11). Kernel size can't be greater than actual input size when input image size too small.

Maybe you can add a parameter to allow dynamic modification of the window size or need padding?

**Comment by VainF** [comment]
Hi!

You can change parameter 'win_size' to modify the window size.

**Comment by One-sixth** [comment]
Thank you for your reply. But I think reducing the window size will have some loss. After downsampling the image, if the downsampled image is smaller than the convolution kernel size, padding the downsampled image. Maybe it can have a better effect.

**Comment by VainF** [comment]
Thanks for your great ideas. 
As far as I know, most of implementations does not pad images. But I think it is OK to pad images if they are too small or maybe we can pad it manually before ssim or ms_ssim. 

Reference:

- [tensorflow](https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/python/ops/image_ops_impl.py)
- [matlab](https://ece.uwaterloo.ca/~z70wang/research/iwssim/)
- [scikit-image](https://github.com/scikit-image/scikit-image/blob/master/skimage/measure/_structural_similarity.py)

**Comment by One-sixth** [comment]
Thank you for your information. I have not other questions now. I thought that padding was needed because I found other repos for padding and dynamic win_size. I don't know which one is correct.

Repo:
https://github.com/Po-Hsun-Su/pytorch-ssim/blob/master/pytorch_ssim/__init__.py
https://github.com/lizhengwei1992/MS_SSIM_pytorch/blob/master/loss.py
