### ISSUE TITLE
The value of SSIM is calculated improperly

### ISSUE THREAD

**Issue by fansuregrin** [VainF/pytorch-msssim#44]
I have 3 images: the `inference`, `img_1`, and `img_2`.

I use this code to calculate SSIM value:
```python
from pytorch_msssim import ssim
ssim_value = ssim(reference.unsqueeze(0), img_1.unsqueeze(0), data_range=255)
output_img = torch.cat((reference, img_1), dim=2)
plt.figure(figsize=(8, 4))
plt.imshow(output_img.numpy().transpose(1, 2, 0))
plt.axis('off')
plt.title(f'ssim = {ssim_value}')
plt.show()
ssim_value = ssim(reference.unsqueeze(0), img_2.unsqueeze(0), data_range=255)
output_img = torch.cat((reference, img_2), dim=2)
plt.figure(figsize=(8, 4))
plt.imshow(output_img.numpy().transpose(1, 2, 0))
plt.axis('off')
plt.title(f'ssim = {ssim_value}')
plt.show()
```
But, results are unexpected...
![image](https://user-images.githubusercontent.com/47016740/224705353-c16d4f97-f403-4255-9259-edb893cd1bc3.png)
![image](https://user-images.githubusercontent.com/47016740/224705372-8d5835bb-438c-47b4-869a-ecdc02fced2d.png)

**Comment by fansuregrin** [comment]
Ok, there are 3 images I used for testing.

(1) the reference, size is 794x481
![142_img_ref](https://user-images.githubusercontent.com/47016740/225245677-08f4b7ea-89ff-4315-b623-d69dc301a878.png)

(2) the img_1, size 794x481
![142_img_1](https://user-images.githubusercontent.com/47016740/225245926-aa3ea91b-64fa-4fcb-8a19-0940c66d0140.png)

(3) the img_2, size 256x256
![142_img_2](https://user-images.githubusercontent.com/47016740/225246098-f6be2236-f122-4dd7-9a88-f9dad398d486.png)

Before calculating ssim, I resize them all into size of 256x256 by using this code:
```
import torchvision.transforms as transforms
resize_tensor = transforms.Resize((256, 256))
```

Thanks for your repley!

**Comment by VainF** [comment]
Sorry @fansuregrin, I can't reproduce this issue. 

Here are my code and results:
```python
import os
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))
from pytorch_msssim import *
import torch
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt 

from pytorch_msssim import ssim, ms_ssim, SSIM, MS_SSIM
npImg = np.array(Image.open("img1.png")).transpose(2,0,1) # C, H, W
img1 = torch.from_numpy(npImg).float().unsqueeze(0) # N,C,H,W

npImg = np.array(Image.open("img2.png")).transpose(2,0,1) # C, H, W
img2 = torch.from_numpy(npImg).float().unsqueeze(0) # N,C,H,W

print(img1.shape)
ssim_value = ssim(img1, img2, data_range=255)
print(ssim_value)
output_img = torch.cat((img1, img2), dim=3)

plt.figure(figsize=(8, 4))
plt.imshow(output_img.numpy()[0].transpose(1,2,0).astype(np.uint8))
plt.axis('off')
plt.title(f'ssim = {ssim_value}')
plt.savefig('output.png')
```
![output](https://user-images.githubusercontent.com/18592211/225334273-9c11f720-4689-4d49-9b52-220a5385bc41.png)

**Comment by fansuregrin** [comment]
@VainF Thanks for your reply. I find the reason. When I calculate the ssim, the value type of image tensor is `torch.uint8`, and I transform it to `torch.float32`, the ssim result is proper!
