### ISSUE TITLE
Implementing SSMI for 3D autoencoders

### ISSUE THREAD

**Issue by MerlinK75** [VainF/pytorch-msssim#52]
Hello
I wanted to try to implement this SSMI for a 3D autoencoder due to the success I have had implementing the loss function in my 2D autoencoder. However, I notice the code is only implemented for 2D images as I get the error: expected stride to be a single integer value or a list of 2 values to match the convolution dimensions, but got stride=[1, 1, 1].

Is there a method where I can implement this loss function for 3D data as well as 2D?

**Comment by lxy51** [comment]
RuntimeError: expected stride to be a single integer value or a list of 2 values to match the convolution dimensions, but got stride=[1, 1, 1]
