### ISSUE TITLE
Apply to 5D tensor?

### ISSUE THREAD

**Issue by John1231983** [VainF/pytorch-msssim#6]
I am working on medical image. It is 5D tensor, such as BxNxDxHxW. Could you please write a test function for 5D tensor? I hear that we can use view function to convert 5D to 4D and then use your code but I am not sure about speed and how to do it? Thanks

https://github.com/VainF/pytorch-msssim/blob/3a42966668094870f58669dc23730e3c58a3c0ea/tests/tests_cuda.py#L9

In additions, we have one bug when the channel is not 3. Let try the script
```

import os
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))
from pytorch_msssim import *
import torch

s = SSIM(data_range=1.)

a = torch.randint(0, 255, size=(10, 2, 64, 64, 64), dtype=torch.float32).cuda() / 255.
b = a * 0.5
B,c,d,h,w = a.size()
a = a.view(B,c,d,-1)
b = b.view(B,c,d,-1)
a.requires_grad = True
b.requires_grad = True
print(a.size(), b.size())

start_record = torch.cuda.Event(enable_timing=True)
end_record = torch.cuda.Event(enable_timing=True)

start_record.record()
for _ in range(500):
    loss = s(a, b)
    loss.backward()
end_record.record()
torch.cuda.synchronize()

print('cuda time: ', start_record.elapsed_time(end_record)/1000)
```

Bug is
```
File "/home/john/pytorch-msssim/pytorch_msssim/ssim.py", line 63, in _ssim
    mu1 = gaussian_filter(X, win)
  File "/home/john/pytorch-msssim/pytorch_msssim/ssim.py", line 34, in gaussian_filter
    out = F.conv2d(input, win, stride=1, padding=0, groups=1)
RuntimeError: Given groups=1, weight of size [3, 1, 1, 11], expected input[2, 2, 64, 4096] to have 1 channels, but got 2 channels instead
```

**Comment by VainF** [comment]
Hi,
MSSSIM & SSIM modules requires `channel` as a parameter. 
I hope the following example is useful.

```
from pytorch_msssim import *
import torch 

s = SSIM(data_range=1., channel=2)

a = torch.randint(0, 255, size=(10, 2, 32, 32, 32), dtype=torch.float32) / 255.
b = a * 0.8
B,c,d,h,w = a.size()
a = a.view(B,c,d,-1)
b = b.view(B,c,d,-1)
print(s(a, b))
```
outputs:
```
tensor(0.9520)
```

**Comment by veritas9872** [comment]
Just use a view with the batch and channel dimensions merged together. Tensor.view(-1, D, H, W) will work.

**Comment by John1231983** [comment]
@VainF : Perfect! it worked
@veritas9872 : Which one should be faster merge batch and channel or merge height and width
```
view(-1,D,H,W)
```
or
```
view(B,C,D,-1)
```

**Comment by John1231983** [comment]
@VainF : I applied your loss to the cyclegan that applied in cycleloss. The range of image is [-0.5,0.5], I have change 
```
s = SSIM(data_range=0.5, channel=2)
```
But the loss becomes a negative value, sometimes positive. Is it normal?

**Comment by VainF** [comment]
> @VainF : I applied your loss to the cyclegan that applied in cycleloss. The range of image is [-0.5,0.5], I have change
> 
> ```
> s = SSIM(data_range=0.5, channel=2)
> ```
> 
> But the loss becomes a negative value, sometimes positive. Is it normal?

`data_range=0.5` means [0, 0.5]
you can change the range by adding 0.5 to outputs and set data_range=1.0

**Comment by John1231983** [comment]
Is it possible to change data_range to accept from [-0.5, 0.5] in the ssim loss. I cannot add 0.5 because it will change the other losses that are using the range [-0.5,0.5]

**Comment by VainF** [comment]
I think adding 0.5 will not affect other losses.
```
loss1 = msssim(output+0.5, input+0.5, data_range=1.0) # out and target are in range of [-0.5, 0.5]
loss2 = other_loss(output, ...)
```

**Comment by John1231983** [comment]
Thanks. I have tried it. But the loss still negative value. Any reason? Not that, other losses are normal

**Comment by veritas9872** [comment]
@John1231983 Are you using merged batch and channel dimensions or merged width and height dimensions? You must use merged batch and height or your results will be incorrect. The 2D convolution applies to the last 2 dimensions, while working in parallel for the other dimensions. 
Using merged height and width will return nonsense outputs, probably explaining the negative values.

Also, a view does not copy memory, so there is almost no extra time needed for returning a new view.

Finally, please note that using merged batch and channel dimensions will give a SSIM for each slice of depth. It will be the average of the SSIM of the 2D images for the 3D volume. If you desire a SSIM for the depth/height axis or depth/width axis, you must reshape your 5D tensor appropriately.

**Comment by John1231983** [comment]
Nice comment @veritas9872 . I will try your way. Could you tell me which win_size do you often use? I use 11 and the SSIM hurt my performance (performance down although the loss always positive value)

**Comment by VainF** [comment]
@John1231983 Sorry for the late replay.
What do you mean by the performance down? In ssim, win_size only determines the size of guassian blur. Did you directly use ssim value as loss?

**Comment by John1231983** [comment]
@VainF yes. I used ssim in cyclegan for cycleloss. Win size is 11 as tuning param. Without ssim, my accuracy is 0.7 and it is 0.65 while adding ssim

**Comment by VainF** [comment]
@John1231983 remeber to take **-1*ssim or 100-ssim** as loss rather than ssim. 
I make a mistake in previous comments and the correct loss should be like this:
```
loss1 = msssim(output+0.5, input+0.5, data_range=1.0) # out and target are in range of [-0.5, 0.5]
loss2 = other_loss(output, ...)
```

**Comment by John1231983** [comment]
@VainF : Good cash. I think it should be
```
loss1 = 1-msssim(output...
```
Because range of ssim is from 0 to 1. I will check the new one

**Comment by VainF** [comment]
:anguished: A mistake again.

**Comment by veritas9872** [comment]
@John1231983 Most people seem to use window size of 11. However, the best outcome depends on what you want as your outcome. There is a paper on the effects of using different window sizes [here](https://github.com/pytorch/pytorch/issues/6934).

**Comment by John1231983** [comment]
Hi. I used ssim in cyclegan and the loss D tends to zero

Anyone try to apply ssim in cyclegsn? I found someone used it and it worked but my case is not

**Comment by VainF** [comment]
@John1231983 , you can scale the ssim value by 100.
I used this repo to train my image compression model and the loss was **100 * (1-msssim)**

Code:
```
class MS_SSIM_Loss(MS_SSIM):
    def forward(self, img1, img2):
        return 100*( 1 - super(MS_SSIM_Loss, self).forward(img1, img2) )
```
